# Generated by Django 4.0.2 on 2022-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('q_img', models.ImageField(upload_to='question/')),
                ('q_ans', models.TextField()),
                ('hint1', models.TextField()),
                ('hint2', models.TextField()),
                ('q_point', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('e_p', models.TextField()),
            ],
        ),
    ]
