# Generated by Django 4.0.2 on 2022-03-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eotyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_points',
            fields=[
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eotyapp.user_register')),
                ('cur_ques', models.IntegerField(default=1)),
                ('hint', models.IntegerField(default=0)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eotyapp.question')),
            ],
        ),
    ]
