# Generated by Django 4.0.2 on 2022-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eotyapp', '0002_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_points',
            name='q_id',
        ),
        migrations.AddField(
            model_name='user_points',
            name='reputation',
            field=models.IntegerField(default=100),
        ),
    ]
