# Generated by Django 4.0.2 on 2022-03-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eotyapp', '0003_remove_user_points_q_id_user_points_reputation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_points',
            old_name='e_id',
            new_name='e_no',
        ),
    ]
