# Generated by Django 4.0.2 on 2022-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eotyapp', '0005_alter_user_points_e_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_points',
            name='first_letter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_points',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
